In [112]:
# https://www.youtube.com/watch?v=1eSmR2EJjYM&t=2108s

In [2]:
import numpy as np

### Create Numpy Arrays from Python Lists

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[1,2.2,3,4.4]

[1, 2.2, 3, 4.4]

In [6]:
# numpy will convert all elements to float
np.array([1,2.2,3,4.4])

array([1. , 2.2, 3. , 4.4])

In [9]:
np.array([1,2.2,3,4.4], dtype='float32')

array([1. , 2.2, 3. , 4.4], dtype=float32)

In [10]:
np.array([1,2.2,3,4.4], dtype='int')

array([1, 2, 3, 4])

In [11]:
a1 = np.array([1,2.2,3,4.4])
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1,2,3],[4,5,6]])
type(a2)

numpy.ndarray

In [13]:
a2.shape

(2, 3)

In [15]:
# number of dimensions
a2.ndim

2

In [16]:
# elements' data type
a2.dtype

dtype('int32')

In [18]:
# num of elements
a2.size

6

### Create Numpy Arrays from Sratch
#### zeros, ones, full, arange, linspace

In [25]:
# create an array with all zeros
np.zeros([2,3],dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
# np.ones((2,3))
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Array with a linear sequence
# start at 0, end at 20, step by 2
# same as built-in range() function
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.arange(0,20,0.1,dtype='float64')

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

In [10]:
np.full((2,3),6.9)

array([[6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9]])

In [14]:
# np.linspace(0,1,5)
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

#### random

In [22]:
np.random.random((4,4))

array([[0.49927728, 0.69203345, 0.60633077, 0.38587273],
       [0.87841314, 0.16129142, 0.45515919, 0.73128011],
       [0.63915322, 0.96799708, 0.07964077, 0.2986579 ],
       [0.86070321, 0.9708358 , 0.27526648, 0.53885436]])

In [34]:
# Reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [53]:
# mean = 0, standard deviation = 1
np.random.normal(0,1,(3,3))

array([[ 0.57659082, -0.20829876,  0.39600671],
       [-1.09306151, -1.49125759,  0.4393917 ],
       [ 0.1666735 ,  0.63503144,  2.38314477]])

In [57]:
np.random.randint(0,10,(2,3))

array([[5, 5, 2],
       [5, 7, 7]])

In [62]:
np.random.rand(4,4)
# np.random.rand()

array([[0.51820071, 0.02566272, 0.20747008, 0.42468547],
       [0.37416998, 0.46357542, 0.27762871, 0.58678435],
       [0.86385561, 0.11753186, 0.51737911, 0.13206811],
       [0.71685968, 0.3960597 , 0.56542131, 0.18327984]])

### Array Indexing & Slicing
#### One-dimensional subarray

In [63]:
x1 = np.random.randint(20, size=6)

In [77]:
x1

array([19, 11, 18, 13,  1,  6])

In [67]:
x1[4], x1[0], x1[-1]

(1, 19, 6)

#### Multi-dimensional array

In [68]:
x2 = np.random.randint(10, size=(3,4))

In [69]:
x2

array([[5, 0, 0, 3],
       [1, 9, 9, 6],
       [6, 7, 8, 8]])

In [75]:
x2[0][0]

5

In [76]:
x2[1,2]

9

#### Slicing

In [ ]:
np[0:10]

In [81]:
x1

array([19, 11, 18, 13,  1,  6])

In [82]:
x1[1:-1:1]

array([11, 18, 13,  1])

In [84]:
x2[:2,:3]

array([[5, 0, 0],
       [1, 9, 9]])

### Reshaping of Arrays & Transpose

In [91]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Array Concatenation and Splitting

In [7]:
x = np.array([1,2,3])
y= np.array([3,2,1])

In [8]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [10]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [4]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Nối theo cột
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
# vertical stack
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

In [19]:
# Thêm 1 cột vào đầu (stack)
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [28]:
y = np.array([[1],[2]])
grid2 = np.array([
    [9,7],[8,6]
])
np.hstack(((y,grid2)))

array([[1, 9, 7],
       [2, 8, 6]])

### Splitting

In [37]:
x  = np.array([1,2,3,99,69,3,2,1])
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 69]), array([3, 2, 1])]

In [30]:
x1, x2, x3 = np.split(x, [3,5])

In [38]:
np.split(x, [2,3,4])

[array([1, 2]), array([3]), array([99]), array([69,  3,  2,  1])]

### Broadcasting and Vectorized operations
Broadcast: chuỗi các hành động để biết đổi matrix shape rồi mới tính toán

In [39]:
a = np.arange(3)
a

array([0, 1, 2])

In [41]:
a + 5 # broadcasting

array([5, 6, 7])

In [48]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
a.shape, b.shape

((3,), (3, 3))

In [50]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [52]:
b * a

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [57]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [58]:
a

array([0, 1, 2])

In [59]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Comparing Arrays
#### Aggregation
Aggregation: performing the same operation on a number of things

In [65]:
massive_array = np.random.random(10000)
massive_array.shape

(10000,)

In [66]:
# %timeit: thoi gian can dung de tinh toan operation nay
%timeit sum(massive_array) # python sum
%timeit np.sum(massive_array)

586 µs ± 8.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.74 µs ± 70.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [68]:
np.mean(massive_array)

0.4977147442682817

In [69]:
np.max(massive_array)

0.9998840701048664

In [71]:
# https://www.mathsisfun.com/data/standard-deviation.html
dog_height = np.array([600,470,170,430,300])
dog_height

array([600, 470, 170, 430, 300])

In [72]:
np.mean(dog_height)

394.0

In [73]:
np.std(dog_height)

147.32277488562318

In [74]:
np.var(dog_height)

21704.0

In [77]:
np.sqrt(np.var(dog_height))

147.32277488562318

### Sorting Arrays
np.sort uses an quicksort algorithm

In [78]:
x  = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [79]:
# argsort: returns the indices of the sorted elements
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

#### Sorting along rows or columns
multi-dimensional array

In [83]:
np.random.seed(42)
A = np.random.randint(0,10,size=(4,6))

In [84]:
A

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [85]:
np.sort(A, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [86]:
np.sort(A, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Linear Algebra

In [107]:
np.random.seed(42)
A=np.random.randint(1,4,size=(3,2))
B=np.random.randint(1,4,size=(2,3))

In [108]:
A

array([[3, 1],
       [3, 3],
       [1, 1]])

In [109]:
B

array([[3, 2, 3],
       [3, 3, 3]])

In [110]:
A@B

array([[12,  9, 12],
       [18, 15, 18],
       [ 6,  5,  6]])

In [111]:
A.dot(B)

array([[12,  9, 12],
       [18, 15, 18],
       [ 6,  5,  6]])

In [113]:
B.dot(A)

array([[18, 12],
       [21, 15]])

In [114]:
# transpose
A.T

array([[3, 3, 1],
       [1, 3, 1]])

#### Dot Product Example

In [117]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [120]:
# Create weekly sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tue","Wed","Thu","Fri"],
                           columns=["Almond","Peanut","Cashew"])
weekly_sales

Almond  Peanut  Cashew
Mon      12      15       0
Tue       3       3       7
Wed       9      19      18
Thu       4       6      12
Fri       1       6       7

In [121]:
# create a price array
butter_prices = np.array([10, 8, 12])
prices = pd.DataFrame(butter_prices.reshape(1,3), index=["Price"],
                      columns=["Almond","Peanut","Cashew"])
prices

Almond  Peanut  Cashew
Price      10       8      12

In [122]:
weekly_sales.shape, prices.shape

((5, 3), (1, 3))

In [126]:
total_prices_per_week = weekly_sales@prices.T
total_prices_per_week

Price
Mon    240
Tue    138
Wed    458
Thu    232
Fri    142

In [128]:
weekly_sales["Total Price"] = total_prices_per_week
weekly_sales

Almond  Peanut  Cashew  Total Price
Mon      12      15       0          240
Tue       3       3       7          138
Wed       9      19      18          458
Thu       4       6      12          232
Fri       1       6       7          142