In [1]:
import numpy as np

### Create Numpy Arrays from Python Lists

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[1,2.2,3,4.4]

[1, 2.2, 3, 4.4]

In [6]:
# numpy will convert all elements to float
np.array([1,2.2,3,4.4])

array([1. , 2.2, 3. , 4.4])

In [9]:
np.array([1,2.2,3,4.4], dtype='float32')

array([1. , 2.2, 3. , 4.4], dtype=float32)

In [10]:
np.array([1,2.2,3,4.4], dtype='int')

array([1, 2, 3, 4])

In [11]:
a1 = np.array([1,2.2,3,4.4])
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1,2,3],[4,5,6]])
type(a2)

numpy.ndarray

In [13]:
a2.shape

(2, 3)

In [15]:
# number of dimensions
a2.ndim

2

In [16]:
# elements' data type
a2.dtype

dtype('int32')

In [18]:
# num of elements
a2.size

6

### Create Numpy Arrays from Sratch
#### zeros, ones, full, arange, linspace

In [25]:
# create an array with all zeros
np.zeros([2,3],dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
# np.ones((2,3))
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])